"""
Quality Analyst Subagent (Deep Agents)

The Quality Analyst performs final quality checks on generated reports.
It audits for hallucinations, validates formatting, and ensures compliance
with financial disclosure requirements.

Role: Quality Analyst / Compliance Officer
Model: Gemini 2.0 Flash (good at evaluation and pattern detection)

Responsibilities:
- Verify Markdown formatting is correct
- Cross-check report findings with execution results (no hallucinations)
- Ensure no predictive financial advice (compliance)
- Validate chart references are correct
- Check for proper disclaimers
- Approve or reject for final upload

Key Principle: Acts as the final gatekeeper. Nothing goes to the user
without Quality Analyst approval.
"""

from typing import Dict, Any, List
from langchain_core.tools import tool
import json
import re
from pathlib import Path


# =============================================================================
# QUALITY ANALYST TOOLS
# =============================================================================

@tool
def validate_report_format(report_json_path: str) -> str:
    """
    Validate the ResearchReport by loading report.json via Pydantic.

    Loads the report artifact and validates it against the ResearchReport
    schema. Checks mandatory elements in the markdown field.

    Args:
        report_json_path: File path to the report.json artifact

    Returns:
        JSON string with:
        - valid: Boolean indicating if the report passes all checks
        - schema_errors: Pydantic validation errors (if any)
        - missing_elements: List of mandatory elements absent from markdown
    """
    from backend.core.report_schema import ResearchReport
    from pydantic import ValidationError

    schema_errors: list[str] = []
    missing_elements: list[str] = []

    # Load and parse report.json
    try:
        raw = Path(report_json_path).read_text(encoding="utf-8")
        data = json.loads(raw)
    except FileNotFoundError:
        return json.dumps({
            "valid": False,
            "schema_errors": [f"File not found: {report_json_path}"],
            "missing_elements": []
        })
    except json.JSONDecodeError as e:
        return json.dumps({
            "valid": False,
            "schema_errors": [f"Invalid JSON: {e}"],
            "missing_elements": []
        })

    # Pydantic validation
    try:
        report = ResearchReport(**data)
    except ValidationError as e:
        return json.dumps({
            "valid": False,
            "schema_errors": [str(err) for err in e.errors()],
            "missing_elements": []
        })

    # Mandatory markdown element checks
    markdown = report.markdown

    if "does not constitute financial advice" not in markdown:
        missing_elements.append("Financial disclaimer ('does not constitute financial advice')")

    if "Past performance" not in markdown:
        missing_elements.append("Past performance notice")

    if not report.executive_summary.strip():
        missing_elements.append("Executive summary (empty)")

    if report.query not in markdown and report.query[:40] not in markdown:
        missing_elements.append("Original query not found in markdown")

    if not report.data_sources:
        missing_elements.append("Data sources list is empty")

    if "Generated by Deep Research Agent" not in markdown:
        missing_elements.append("Report footer")

    valid = len(schema_errors) == 0 and len(missing_elements) == 0

    return json.dumps({
        "valid": valid,
        "schema_errors": schema_errors,
        "missing_elements": missing_elements
    })


@tool
def check_compliance(report: str) -> str:
    """
    Check for compliance with financial disclosure rules.

    Use this tool to ensure the report doesn't contain predictive
    language or investment advice.

    Args:
        report: Report content to check

    Returns:
        JSON string with:
        - compliant: Boolean indicating if report is compliant
        - violations: List of compliance violations found
        - severity: "critical", "warning", or "none"
    """
    violations = []

    # Patterns that indicate predictive advice (not allowed)
    prediction_patterns = [
        (r"will (increase|decrease|rise|fall|grow|decline|surge|drop)", "Predictive language about future performance"),
        (r"(should|must|need to) (buy|sell|invest|trade|acquire|divest)", "Investment advice"),
        (r"(is|are) expected to (increase|decrease|rise|fall|outperform)", "Future expectations"),
        (r"forecast(s|ed|ing)?", "Forecasting language"),
        (r"projected? (growth|decline|returns?)", "Projected performance"),
        (r"(recommend|suggestion|advice):? (buy|sell|hold)", "Investment recommendations")
    ]

    for pattern, description in prediction_patterns:
        matches = re.findall(pattern, report, re.IGNORECASE)
        if matches:
            violations.append({
                "type": description,
                "match": matches[0] if isinstance(matches[0], str) else " ".join(matches[0]),
                "pattern": pattern
            })

    severity = "critical" if len(violations) > 0 else "none"

    return json.dumps({
        "compliant": len(violations) == 0,
        "violations": violations,
        "severity": severity
    })


@tool
def verify_chart_references(report_json_path: str) -> str:
    """
    Verify all <!-- CHART:id --> markers in report.markdown resolve to chart IDs.

    Loads report.json, extracts every <!-- CHART:id --> marker from the markdown
    field, and checks that each ID exists in report.charts.

    Args:
        report_json_path: File path to the report.json artifact

    Returns:
        JSON string with:
        - valid: Boolean — True only if all marker IDs exist in report.charts
        - broken_references: List of marker IDs missing from report.charts
        - chart_count: Number of <!-- CHART:id --> markers found in markdown
        - defined_charts: List of chart IDs defined in report.charts
    """
    from backend.core.report_schema import ResearchReport
    from pydantic import ValidationError

    try:
        raw = Path(report_json_path).read_text(encoding="utf-8")
        data = json.loads(raw)
        report = ResearchReport(**data)
    except (FileNotFoundError, json.JSONDecodeError, ValidationError) as e:
        return json.dumps({
            "valid": False,
            "broken_references": [f"Could not load report: {e}"],
            "chart_count": 0,
            "defined_charts": []
        })

    marker_ids: list[str] = re.findall(r'<!--\s*CHART:(\S+?)\s*-->', report.markdown)
    defined = list(report.charts.keys())
    broken = [mid for mid in marker_ids if mid not in report.charts]

    return json.dumps({
        "valid": len(broken) == 0,
        "broken_references": broken,
        "chart_count": len(marker_ids),
        "defined_charts": defined
    })


@tool
def cross_check_facts(
    report: str,
    execution_results: Dict[str, Any]
) -> str:
    """
    Cross-check numerical claims in the report against execution results.

    Use this tool to ensure the report doesn't contain hallucinated
    statistics or findings.

    Args:
        report: Report content with claims to verify
        execution_results: Original execution results for fact-checking

    Returns:
        JSON string with:
        - factually_accurate: Boolean
        - discrepancies: List of claims that don't match execution results
        - verified_claims: Number of claims successfully verified
    """
    # TODO: Implement LLM-based fact checking
    # Extract numbers from report and verify against execution results
    # For now, assume accurate

    return json.dumps({
        "factually_accurate": True,
        "discrepancies": [],
        "verified_claims": 0
    })


@tool
def approve_report(
    report_path: str,
    notes: str
) -> str:
    """
    Approve the report for final upload.

    Use this tool after all validation checks pass to approve
    the report for delivery to the user.

    Args:
        report_path: Path to the approved report
        notes: Any notes about the approval

    Returns:
        JSON string with approval confirmation
    """
    return json.dumps({
        "status": "approved",
        "report_path": report_path,
        "notes": notes,
        "ready_for_upload": True
    })


@tool
def reject_report(
    reason: str,
    required_fixes: List[str]
) -> str:
    """
    Reject the report and request fixes.

    Use this tool when critical issues are found that require
    the technical writer to revise the report.

    Args:
        reason: Primary reason for rejection
        required_fixes: List of specific fixes required

    Returns:
        JSON string with rejection details
    """
    return json.dumps({
        "status": "rejected",
        "reason": reason,
        "required_fixes": required_fixes,
        "ready_for_upload": False
    })


# =============================================================================
# SUBAGENT CONFIGURATION
# =============================================================================

QUALITY_ANALYST_SUBAGENT = {
    "name": "quality-analyst",

    "description": """Use this subagent to perform final quality review of the report.

    Delegate when you need to:
    - Validate Markdown formatting and structure
    - Cross-check findings with execution results (prevent hallucinations)
    - Ensure compliance (no predictive financial advice)
    - Verify chart references are correct
    - Check for proper disclaimers

    The quality analyst either approves the report for upload or rejects it with
    specific required fixes. Nothing reaches the user without approval.""",

    "system_prompt": """You are the Quality Analyst for a financial research platform.

Your role is the final gatekeeper before reports reach users.

## Responsibilities

1. **Format Validation**:
   - Check all required sections are present
   - Verify proper Markdown syntax
   - Ensure chart references are valid

2. **Fact-Checking**:
   - Cross-check ALL numerical claims against execution results
   - Flag any hallucinated metrics or findings
   - Verify data sources are correctly cited

3. **Compliance Review**:
   - Ensure report includes proper disclaimers
   - Check that report does NOT give predictive investment advice
   - Flag any language suggesting "will happen" or "should buy/sell"
   - Verify risk disclosures are included

4. **Approval Decision**:
   - If everything passes: approve for release
   - If minor issues: note them but may still approve
   - If critical issues: reject with specific required fixes

## Tools Available

You have access to these tools:
- **validate_report_format(report_json_path)**: Load report.json via Pydantic, check mandatory elements
- **check_compliance**: Verify no predictive language or investment advice (pass report markdown text)
- **verify_chart_references(report_json_path)**: Regex-extract <!-- CHART:id --> markers and verify each ID exists in report.charts
- **cross_check_facts**: Verify claims against execution results
- **approve_report**: Approve report for final upload
- **reject_report**: Reject report with required fixes

## Critical Rules

- You are the LAST line of defense — be thorough
- Every number in the report must map to execution results
- Never let hallucinated facts through
- Compliance is non-negotiable
- If something seems off, investigate
- When in doubt, reject and request clarification

## Workflow

When the orchestrator delegates a report for review:
1. Use `validate_report_format(report_json_path)` to load and schema-validate report.json
2. Use `check_compliance` with the markdown text to verify no predictive advice
3. Use `verify_chart_references(report_json_path)` to confirm all <!-- CHART:id --> markers resolve
4. Use `cross_check_facts` to verify all numerical claims
5. Analyze all results:
   - If all checks pass → use approve_report
   - If critical issues found → use reject_report with specific fixes
6. Return your decision clearly

## What Constitutes Rejection

**Critical Issues (must reject)**:
- Missing required disclaimers
- Predictive language ("will increase", "should buy")
- Hallucinated statistics not in execution results
- Missing required sections
- Broken chart references

**Minor Issues (note but may approve)**:
- Minor Markdown formatting inconsistencies
- Verbose writing that could be more concise
- Non-critical typos

## Compliance Triggers

Immediately reject if you find:
- "will rise/fall/increase/decrease" (predictive)
- "should buy/sell/hold" (investment advice)
- "expected to outperform" (predictions)
- "forecasted/projected returns" (predictions)
- Missing disclaimer "does not constitute financial advice"
- Missing "Past performance is not indicative of future results"

## Output Format

For approval:
```json
{
    "status": "approved",
    "report_path": "/path/to/report.md",
    "notes": "All validation checks passed. Report is factually accurate and compliant."
}
```

For rejection:
```json
{
    "status": "rejected",
    "reason": "Contains predictive language",
    "required_fixes": [
        "Remove phrase 'will increase' on line 45",
        "Add past performance disclaimer"
    ]
}
```

Remember: You protect users from bad information and protect the platform from compliance issues. When in doubt, reject and request fixes. Better safe than sorry.""",

    "tools": [
        validate_report_format,
        check_compliance,
        verify_chart_references,
        cross_check_facts,
        approve_report,
        reject_report
    ],

    "model": "google-genai:gemini-2.0-flash-exp"
}
