"""Stable method identifiers emitted by quant macro helpers."""

from __future__ import annotations

from ._utils import (
    DEFAULT_REGIME_CATEGORIES,
    DEFAULT_REGIME_WEIGHTS,
    METHOD_ANALOG_WINDOW_COMPARISON,
    METHOD_COMPOSITE_PREDICTIVE_INDICATOR,
    METHOD_DIRECT_OLS_FORECAST,
    METHOD_EVENT_SIGNAL_BACKTEST,
    METHOD_HISTORICAL_SCENARIO_REPLAY,
    METHOD_LEAD_LAG_CORRELATION,
    METHOD_OLS_REGRESSION,
    METHOD_PERIOD_KEY_ALIGNMENT,
    METHOD_RECESSION_REGIME_CLASSIFIER,
    METHOD_RECESSION_WINDOW_SUMMARY,
    METHOD_ROLLING_CORRELATION,
    METHOD_SEC_COMPANY_FACTS_SUMMARY,
    METHOD_SIGNAL_FRAMEWORK_BACKTEST,
    METHOD_STATIONARITY_CHECK,
    METHOD_WALK_FORWARD_OLS_BACKTEST,
)

__all__ = [
    "DEFAULT_REGIME_CATEGORIES",
    "DEFAULT_REGIME_WEIGHTS",
    "METHOD_ANALOG_WINDOW_COMPARISON",
    "METHOD_COMPOSITE_PREDICTIVE_INDICATOR",
    "METHOD_DIRECT_OLS_FORECAST",
    "METHOD_EVENT_SIGNAL_BACKTEST",
    "METHOD_HISTORICAL_SCENARIO_REPLAY",
    "METHOD_LEAD_LAG_CORRELATION",
    "METHOD_OLS_REGRESSION",
    "METHOD_PERIOD_KEY_ALIGNMENT",
    "METHOD_RECESSION_REGIME_CLASSIFIER",
    "METHOD_RECESSION_WINDOW_SUMMARY",
    "METHOD_ROLLING_CORRELATION",
    "METHOD_SEC_COMPANY_FACTS_SUMMARY",
    "METHOD_SIGNAL_FRAMEWORK_BACKTEST",
    "METHOD_STATIONARITY_CHECK",
    "METHOD_WALK_FORWARD_OLS_BACKTEST",
]
